network/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path('post/create/', views.new_post, name='create_post'),
    path("edit/<str:post_id>", views.edit, name="edit"), 
    path('profile/<str:username>/', views.profile, name='profile'),
    path('following/', views.following, name='following'),
    path("like/<int:id>/", views.like, name="like"),
    path("follow/<int:id>/", views.follow, name="follow"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register, name="register")
]

project4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
]

network/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
import datetime


class User(AbstractUser):
    pass


class Post(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=160, default=None)
    post_date = models.DateTimeField(default=datetime.datetime.now)

    def __str__(self):
        return f"{self.user} to {self.text}"


class Follower(models.Model):
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower', default=None)
    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following', default=None)

    class Meta:
        unique_together = (('follower', 'following'),)
    
    def __str__(self):
            return f"{self.follower} : {self.following}"


class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, default=None)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    class Meta:
        unique_together = (('post', 'user'),)

    def __str__(self):
        return f"{self.post} : {self.user}"

network/forms.py
from django import forms

class NewPostForm(forms.Form):
    post_text = forms.Field(widget=forms.Textarea(
        {'rows': '3', 'maxlength': 160, 'class': 'form-control', 'placeholder': "Post Something"}), label="New Post", required=True)

network/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.db.models import OuterRef, Count
from django.core.paginator import Paginator


from django.views.decorators.csrf import csrf_exempt
import json

from .forms import NewPostForm
from .models import User, Like, Post, Follower


def index(request):
    if request.user.is_authenticated:
        user = request.session['_auth_user_id']
        likes = Like.objects.filter(post=OuterRef('id'), user_id = user)
        posts = Post.objects.filter().order_by('-post_date')
    else:
        posts = Post.objects.order_by('-post_date').all()
    
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'posts': page_obj,
        'new_post': NewPostForm(),
    }
    return render(request, "network/index.html", context)


def new_post(request):
    form = NewPostForm(request.POST)
    
    if form.is_valid():
        user = User.objects.get(id=request.session['_auth_user_id'])
        text = form.cleaned_data['post_text']
        post = Post(user=user,text=text)
        post.save()
        return HttpResponseRedirect(reverse('index'))
    else:
        return HttpResponseRedirect(reverse('index'))


@csrf_exempt
def edit(request, post_id):
    post = Post.objects.get(id=post_id)

    if request.method == "PUT":
        data = json.loads(request.body)
        if data.get("post") is not None:
            post.text = data["post"]
        post.save()
        return HttpResponse(status=204)


def profile(request, username):
    following = 0
    profiles_user = User.objects.get(username=username)
    if request.user.is_authenticated:
        logged_in = request.session['_auth_user_id']
        following = Follower.objects.filter(follower=logged_in, following=profiles_user).count()
        like = Like.objects.filter(post=OuterRef('id'), user_id= logged_in)
        posts = Post.objects.filter(user=profiles_user).order_by('-post_date').annotate(current_like=Count(like.values('id')))
        if following >= 1:
            result = 'Unfollow'
        else: 
            result = 'Follow'
    else:
        posts = Post.objects.filter(user=profiles_user).order_by('-post_date')  

    total_followers = Follower.objects.filter(following=profiles_user).count()
    total_following = Follower.objects.filter(follower=profiles_user).count()
    
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'user_profile':profiles_user, 
        'posts':page_obj, 
        'following': following, 
        'total_followers':total_followers,
        'total_following': total_following,
        'new_post': NewPostForm(), 
        'result': result
    }
    return render(request, 'network/profile.html', context)


def like(request, id):
    css = 'fas fa-heart'
    user = User.objects.get(id=request.session['_auth_user_id'])
    post = Post.objects.get(id=id)
    like = Like.objects.get_or_create(user=user, post=post)

    if not like[1]:
        css = 'far fa-heart'
        Like.objects.filter(user=user, post=post).delete()

    total_likes = Like.objects.filter(post=post).count()
    
    context = {
        'like': id,
        'css_marker':  css,
        'total_likes': total_likes
    }
    return JsonResponse(context)


def follow(request, id):
    result = 'follow'
    user = User.objects.get(id = request.session['_auth_user_id'])
    following_user = User.objects.get(id=id)
    follower = Follower.objects.get_or_create(follower=user, following=following_user)

    if not follower[1]:
        Follower.objects.filter(follower=user, following=following_user).delete()
        result = 'unfollow'
    
    total_followers = Follower.objects.filter(following=following_user).count()
    context = {
        'result': result,
        'total_followers': total_followers
    }
    return JsonResponse(context)


def following(request):
    user = request.session['_auth_user_id']
    followers = Follower.objects.filter(follower=user)
    posts = Post.objects.filter(user_id__in=followers.values('following_id').order_by('-id'))

    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'posts': page_obj,
        'new_post': NewPostForm()
    }
    return render(request, 'network/following.html', context)


#------------login/register ---------------------
def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "network/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "network/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "network/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "network/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "network/register.html")

network/templates/network/following.html
{% extends "network/layout.html" %}

{% block body %}
<h1>Following</h1>
{% include "partials/_post_form.html" %}
{% include 'partials/_all_posts.html' %}
{% endblock %}

network/templates/network/index.html
{% extends "network/layout.html" %}
{% block title %}CS50's Network {% endblock title%}
{% block body %}
    {% include "partials/_post_form.html" %}
    {% include 'partials/_all_posts.html' %}
{% endblock %}

network/templates/network/layout.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" rel="stylesheet">
        <link href="{% static 'css/styles.css' %}" rel="stylesheet">
        <title>{% block title %}Social Network{% endblock %}</title>
    </head>
    <body>
        <!--navbar-->
        {% include 'partials/_navbar.html' %}

        <div class = 'container'>
            {% block body %}
            {% endblock %}
        </div>

        <!--paginator-->
        {% include 'partials/_paginator.html' %}

        <!-- Option 1: Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <script src="{% static 'js/script.js' %}"></script>
    </body>
</html>

network/templates/network/login.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

network/templates/network/profile.html
{% extends "network/layout.html" %}
{% block title %}{{user_profile.username}}'s Profile {% endblock title%}
{% block body %}
<div class="card">
        {% include "partials/_post_form.html" %}
        <div class="card-body ">
            <h5 class="card-text">{{user_profile}} has <span id="sp_followers">{{total_followers}}</span> followers</h5>
            <h5 class="card-text">{{user_profile}} is following <span id="sp_following">{{total_following}}</span> accounts </h5>
            <p class="card-text"><small class="text-muted"></small></p>
            {% if user.is_authenticated and user.id != user_profile.id %}
                <p class="card-text">
                    <button id="btnfollow" data-id="{{user_profile.id}}" class="btn btn-outline-dark">{{result}} </button>
                </p>
            {% endif %}
        </div>
        {% include 'partials/_all_posts.html' %}
    </div>
{% endblock %}

network/templates/network/register.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}

network/templates/partials/_all_posts.html
<!--post list-->
<div id="posts">
    {% for post in posts %} 
        <div class="border border-secondary rounded p-3 mt-2">
            <h4><a href="{% url 'profile' post.user.username %}">{{ post.user }}</a></h4>
            <div id="post-text-{{post.id}}">{{ post.text }}</div>
            {% if post.user.id == user.id %}
                <div id="{{post.id}}" class="text-primary edit_post">Edit Post</div>
            {% endif %}
            
            <textarea class="form-control mb-2" id="edit-box-{{post.id}}" name="edit-box" style="display:none;"></textarea>
            <button id="edit-btn-{{post.id}}" class="btn btn-primary" style="display:none;">Save</button>

            <hr>
            <div data-id="{{post.id}}" class="card-link {% if post.current_like > 0 %} fas {% else %} far {% endif %} fa-heart">
                &nbsp <small class="text-muted">{{post.like_set.count}}</small>
            </div>
            <p class="card-text"><small class="text-muted">{{post.post_date}}</small></p> 
            <p><small>comment</small></p>
        </div>
    {% empty %}
        <li>no post</li>
    {% endfor %}
</div>

network/templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Network</a>
    <div>
    <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'profile' user.username %}"><strong>{{ user.username }}</strong></a>
            </li>
        {% endif %}
        <li class="nav-item">
        <a class="nav-link" href="{% url 'index' %}">All Posts</a>
        </li>
        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'following' %}">Following</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Log In</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'register' %}">Register</a>
            </li>
        {% endif %}
    </ul>
    </div>
</nav>

network/templates/partials/_paginator.html
<!--paginator-->

<ul class="pagination justify-content-center">
    {% if posts.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ posts.previous_page_number }}">
                Previous
            </a>
        </li>
    {% endif %}
    {%if posts.paginator.num_pages > 1 %}
        {% for num in posts.paginator.page_range %}
            {% if posts.number == num %}
                <li class="page-item active">
                    <a class="page-link">{{ num }}</a>
                </li>
            {% elif num > posts.number|add:'-3' and num < posts.number|add:'3' %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
            {% endif %}
        {% endfor %}
    {% endif %}
    {% if posts.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ posts.next_page_number }}">
            Next
        </a>
    </li>
    {% endif %}
</ul>

network/templates/partials/_post_form.html
{% if user.is_authenticated %}
<div class="card">
    <div class="card-body">
        <form action="{% url 'create_post' %}" method="post">
            {% csrf_token %}
            <div class="form-group text-center">
                <label for="post_text" class="h4"> Hello {{user.username}}, Post Something Cool! </label>
                {{ new_post.post_text }}
            </div>
            <button type="submit" class="btn btn-primary btn-sm">Upload Post</button>
        </form>
    </div>
</div>
{%endif%}